/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2ipc1;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class AgregarEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form AgregarEstudiante
     */
    public AgregarEstudiante() {
        initComponents();
        setLocationRelativeTo(null);

        //Generar Numero Random Para contrasena
        txtcontra.setText(String.valueOf(random()));
        txtcontra.setEditable(false);

    }

    public int random() {

        int numero;

        numero = (int) (Math.random() * (151 - 50) + 50);

        return numero;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcarnet = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txtcredito = new javax.swing.JTextField();
        txtcontra = new javax.swing.JTextField();
        txtdpi = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        bagregar = new javax.swing.JButton();
        bsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Agregar Estudiante");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 10, 280, 40);

        jLabel2.setText("Carnet");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 80, 110, 20);

        jLabel3.setText("Dpi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 130, 70, 20);

        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 110, 20);

        jLabel5.setText("Apellido");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 230, 110, 20);

        jLabel6.setText("Correo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(330, 230, 70, 20);

        jLabel7.setText("Direccion");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(330, 80, 60, 20);

        jLabel8.setText("No. Creditos");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(330, 130, 70, 20);

        jLabel9.setText("Contraseña");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(330, 180, 70, 20);

        txtcarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcarnetActionPerformed(evt);
            }
        });
        jPanel1.add(txtcarnet);
        txtcarnet.setBounds(70, 80, 180, 30);
        jPanel1.add(txtdireccion);
        txtdireccion.setBounds(400, 80, 150, 30);

        txtcredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcreditoActionPerformed(evt);
            }
        });
        jPanel1.add(txtcredito);
        txtcredito.setBounds(400, 130, 150, 30);

        txtcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraActionPerformed(evt);
            }
        });
        jPanel1.add(txtcontra);
        txtcontra.setBounds(400, 180, 150, 30);
        jPanel1.add(txtdpi);
        txtdpi.setBounds(70, 130, 180, 30);
        jPanel1.add(txtnombre);
        txtnombre.setBounds(70, 180, 180, 30);
        jPanel1.add(txtapellido);
        txtapellido.setBounds(70, 230, 180, 30);
        jPanel1.add(txtcorreo);
        txtcorreo.setBounds(400, 230, 150, 30);

        bagregar.setBackground(new java.awt.Color(0, 204, 51));
        bagregar.setText("Agregar");
        bagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagregarActionPerformed(evt);
            }
        });
        jPanel1.add(bagregar);
        bagregar.setBounds(130, 300, 120, 40);

        bsalir.setBackground(new java.awt.Color(255, 0, 0));
        bsalir.setText("Salir");
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });
        jPanel1.add(bsalir);
        bsalir.setBounds(330, 300, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcreditoActionPerformed

    private void txtcarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcarnetActionPerformed

    private void txtcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtcontraActionPerformed

    private void bagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagregarActionPerformed
        // TODO add your handling code here:
        String apellido = txtapellido.getText();
        String nombre = txtnombre.getText();
        String correo = txtcorreo.getText();
        String direccion = txtdireccion.getText();
        String dpi = txtdpi.getText();
        String carnet = txtcarnet.getText();
        String contra = txtcontra.getText();
        String credito = txtcredito.getText();

        if (apellido.length() != 0 && nombre.length() != 0 && correo.length() != 0 && direccion.length() != 0
                && dpi.length() != 0 && carnet.length() != 0) {

            if (Proyecto2IPC1.estudiante.CDPIExiste()) {
                Proyecto2IPC1.estudiante.IngresarEstudiante(carnet, dpi, nombre+" "+apellido, correo, direccion, credito,carnet+contra);
                
                txtcontra.setText(String.valueOf(random()));

                txtapellido.setText(null);
                txtnombre.setText(null);
                txtcorreo.setText(null);
                txtdireccion.setText(null);
                txtdpi.setText(null);
                txtcarnet.setText(null);
                txtcredito.setText(null);
                JOptionPane.showMessageDialog(null, "Se ha ingresado con Exito", "Confirmacion", 1);
            }else{
                JOptionPane.showMessageDialog(null, "Carnet/Dpi ya existente", "Error", 1);
            }

            
        } else {
            JOptionPane.showMessageDialog(null, "No ha ingresado todos los datos", "Error", 1);
        }

        /*txtapellido.setText(null);
        txtnombre.setText(null);
        txtcorreo.setText(null);
        txtdireccion.setText(null);
        txtdpi.setText(null);
        txtcarnet.setText(null);
        txtcredito.setText(null);*/

    }//GEN-LAST:event_bagregarActionPerformed

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        // TODO add your handling code here:
        AdministrarEstudiantes administrador = new AdministrarEstudiantes();
        administrador.setVisible(true);
        AgregarEstudiante.this.dispose();
        Proyecto2IPC1.estudiante.MostrarEstudiantes();
    }//GEN-LAST:event_bsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagregar;
    private javax.swing.JButton bsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtapellido;
    public static javax.swing.JTextField txtcarnet;
    private javax.swing.JTextField txtcontra;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtcredito;
    private javax.swing.JTextField txtdireccion;
    public static javax.swing.JTextField txtdpi;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
