/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2ipc1;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class AgregarCursos extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCursos
     */
    public AgregarCursos() {
        initComponents();
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bagregar = new javax.swing.JButton();
        bsalir = new javax.swing.JButton();
        txtcodigo = new javax.swing.JTextField();
        txtcurso = new javax.swing.JTextField();
        txtcatedratico = new javax.swing.JTextField();
        txtcredito = new javax.swing.JTextField();
        txtlab = new javax.swing.JTextField();
        txtpre = new javax.swing.JTextField();
        txtpost = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtseccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Agregar Curso");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 20, 280, 50);

        jLabel2.setText("Codigo Curso");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 90, 80, 20);

        jLabel3.setText("Curso");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 150, 60, 14);

        jLabel4.setText("Catedratico");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 210, 70, 20);

        jLabel5.setText("Creditos");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(14, 270, 50, 20);

        jLabel6.setText("Laboratorio");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 100, 80, 20);

        jLabel7.setText("PreRequisito");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 150, 80, 20);

        jLabel8.setText("PostRequisito");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(300, 210, 90, 30);

        bagregar.setBackground(new java.awt.Color(51, 204, 0));
        bagregar.setText("Agregar");
        bagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagregarActionPerformed(evt);
            }
        });
        jPanel1.add(bagregar);
        bagregar.setBounds(130, 320, 110, 50);

        bsalir.setBackground(new java.awt.Color(255, 0, 0));
        bsalir.setText("Salir");
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });
        jPanel1.add(bsalir);
        bsalir.setBounds(340, 320, 110, 50);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(100, 90, 160, 30);
        jPanel1.add(txtcurso);
        txtcurso.setBounds(100, 150, 160, 30);
        jPanel1.add(txtcatedratico);
        txtcatedratico.setBounds(100, 210, 160, 30);
        jPanel1.add(txtcredito);
        txtcredito.setBounds(100, 260, 160, 30);

        txtlab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlabActionPerformed(evt);
            }
        });
        jPanel1.add(txtlab);
        txtlab.setBounds(400, 100, 150, 30);

        txtpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreActionPerformed(evt);
            }
        });
        jPanel1.add(txtpre);
        txtpre.setBounds(400, 150, 150, 30);
        jPanel1.add(txtpost);
        txtpost.setBounds(400, 210, 150, 30);

        jLabel9.setText("Seccion");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(300, 270, 70, 14);

        txtseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseccionActionPerformed(evt);
            }
        });
        jPanel1.add(txtseccion);
        txtseccion.setBounds(400, 260, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreActionPerformed

    private void txtlabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlabActionPerformed

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        // TODO add your handling code here:
        new AdministrarCursos().setVisible(true);
        AgregarCursos.this.dispose();
    }//GEN-LAST:event_bsalirActionPerformed

    private void bagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagregarActionPerformed
        // TODO add your handling code here:
        String codigo=txtcodigo.getText();
        String curso = txtcurso.getText();
        String catedratico = txtcatedratico.getText();
        String credito = txtcredito.getText();
        String lab = txtlab.getText();
        String pre = txtpre.getText();
        String post = txtpost.getText();
        String seccion=txtseccion.getText();
        
        if(codigo.length()!=0&&curso.length()!=0&&catedratico.length()!=0&&credito.length()!=0&&
                lab.length()!=0&&pre.length()!=0&&post.length()!=0){
            if(Proyecto2IPC1.curso.CursoExiste()){
                Proyecto2IPC1.curso.agregarCurso(codigo, curso, catedratico, credito, lab,seccion, pre, post);
                ///////Agregar un numero random para añadir contraseña al catedratico
                
                
                txtcodigo.setText(null);
                txtcurso.setText(null);
                txtcatedratico.setText(null);
                txtcredito.setText(null);
                txtlab.setText(null);
                txtseccion.setText(null);
                txtpre.setText(null);
                txtpost.setText(null);
                
                JOptionPane.showMessageDialog(null, "Se ha ingresado con Exito", "Confirmacion", 1);
            }else{
                JOptionPane.showMessageDialog(null, "Codigo de Curso ya existente", "Error", 1);
            }
            
            
        }else{
            JOptionPane.showMessageDialog(null, "No ha ingresado todos los datos", "Error", 1);
        }
    }//GEN-LAST:event_bagregarActionPerformed

    private void txtseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtseccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagregar;
    private javax.swing.JButton bsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcatedratico;
    public static javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcredito;
    private javax.swing.JTextField txtcurso;
    private javax.swing.JTextField txtlab;
    private javax.swing.JTextField txtpost;
    private javax.swing.JTextField txtpre;
    private javax.swing.JTextField txtseccion;
    // End of variables declaration//GEN-END:variables
}
