/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2ipc1;

import javax.swing.JOptionPane;
import static proyecto2ipc1.ModificarEstudiante.jComboBox1;

/**
 *
 * @author USUARIO
 */
public class EliminarEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form EliminarEstudiante
     */
    public EliminarEstudiante() {
        initComponents();
        setLocationRelativeTo(null);
        
        ///////////Bloquear TextField////////
        txtdpi.setEditable(false);
        txtcontra.setEditable(false);
        
        
        ////////////Carnets//////////////////////////////////
        NodoEstudiante aux;
        aux = Proyecto2IPC1.estudiante.primero;
        do {
            jComboBox1.addItem(aux.carnet);
            aux = aux.siguiente;
        } while (aux != Proyecto2IPC1.estudiante.primero);
        ////////////////////////////////////////////////////
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bobtener = new javax.swing.JButton();
        beliminar = new javax.swing.JButton();
        bsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtdpi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        txtcredito = new javax.swing.JTextField();
        txtcontra = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Eliminar Estudiante");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 340, 50);

        bobtener.setBackground(new java.awt.Color(0, 255, 204));
        bobtener.setText("Obtener");
        bobtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bobtenerActionPerformed(evt);
            }
        });
        jPanel1.add(bobtener);
        bobtener.setBounds(50, 300, 110, 50);

        beliminar.setBackground(new java.awt.Color(102, 255, 0));
        beliminar.setText("Eliminar");
        beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminarActionPerformed(evt);
            }
        });
        jPanel1.add(beliminar);
        beliminar.setBounds(210, 300, 120, 50);

        bsalir.setBackground(new java.awt.Color(204, 204, 0));
        bsalir.setText("Salir");
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });
        jPanel1.add(bsalir);
        bsalir.setBounds(380, 300, 120, 50);

        jLabel2.setText("Carnet");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 70, 20);

        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(90, 70, 160, 30);

        jLabel3.setText("Dpi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 130, 60, 20);
        jPanel1.add(txtdpi);
        txtdpi.setBounds(90, 120, 160, 30);

        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 50, 14);
        jPanel1.add(txtnombre);
        txtnombre.setBounds(90, 170, 160, 30);

        jLabel5.setText("Apellido");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 230, 40, 14);
        jPanel1.add(txtapellido);
        txtapellido.setBounds(90, 220, 160, 30);

        jLabel6.setText("Direccion");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 80, 50, 14);

        jLabel7.setText("No.Credito");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(300, 130, 70, 14);

        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(296, 180, 70, 14);

        jLabel9.setText("Correo");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(310, 230, 50, 14);
        jPanel1.add(txtdireccion);
        txtdireccion.setBounds(380, 70, 150, 30);

        txtcredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcreditoActionPerformed(evt);
            }
        });
        jPanel1.add(txtcredito);
        txtcredito.setBounds(380, 120, 150, 30);

        txtcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraActionPerformed(evt);
            }
        });
        jPanel1.add(txtcontra);
        txtcontra.setBounds(380, 170, 150, 30);

        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtcorreo);
        txtcorreo.setBounds(380, 220, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcreditoActionPerformed

    private void txtcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraActionPerformed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        // TODO add your handling code here:
        AdministrarEstudiantes administrador = new AdministrarEstudiantes();
        administrador.setVisible(true);
        EliminarEstudiante.this.dispose();
    }//GEN-LAST:event_bsalirActionPerformed

    private void bobtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bobtenerActionPerformed
        // TODO add your handling code here:
        NodoEstudiante aux;
        aux = Proyecto2IPC1.estudiante.primero;
        do {
            if(jComboBox1.getSelectedItem()==aux.carnet){
                txtdpi.setText(aux.dpi);
                //txtapellido.setText(aux.Apellido);
                txtnombre.setText(aux.Nombre);
                txtdireccion.setText(aux.direccion);
                txtcredito.setText(aux.credito);
                txtcontra.setText(aux.contrasena);
                txtcorreo.setText(aux.correo);
            }
            aux = aux.siguiente;
        } while (aux != Proyecto2IPC1.estudiante.primero);
    }//GEN-LAST:event_bobtenerActionPerformed

    private void beliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminarActionPerformed
        // TODO add your handling code here:
        NodoEstudiante posicion_actual;
        NodoEstudiante anterior;
        posicion_actual=Proyecto2IPC1.estudiante.primero;
        anterior=Proyecto2IPC1.estudiante.ultimo;
        
        do {
            if(jComboBox1.getSelectedItem()==posicion_actual.carnet){
                if(posicion_actual==Proyecto2IPC1.estudiante.primero){
                    Proyecto2IPC1.estudiante.primero=Proyecto2IPC1.estudiante.primero.siguiente;
                    Proyecto2IPC1.estudiante.ultimo.siguiente=Proyecto2IPC1.estudiante.primero;
                    Proyecto2IPC1.estudiante.primero.anterior=Proyecto2IPC1.estudiante.ultimo;
                    JOptionPane.showMessageDialog(null, "Se ha realizado Eliminado la primera posicion", "Eliminar", 1);
                }else if(posicion_actual==Proyecto2IPC1.estudiante.ultimo){
                     Proyecto2IPC1.estudiante.ultimo= Proyecto2IPC1.estudiante.ultimo.anterior;
                     Proyecto2IPC1.estudiante.primero.anterior= Proyecto2IPC1.estudiante.ultimo;
                     Proyecto2IPC1.estudiante.ultimo.siguiente= Proyecto2IPC1.estudiante.primero;  
                     JOptionPane.showMessageDialog(null, "Se ha Eliminado la ultima posicion", "Eliminar", 1);
                      
                    
                }else{
                     anterior.siguiente=posicion_actual.siguiente;
                     posicion_actual.siguiente.anterior=anterior;
                     JOptionPane.showMessageDialog(null, "Se ha eliminado el usuario", "Eliminar", 1);
                }
                /*txtdpi.setText(aux.dpi);
                txtapellido.setText(aux.Apellido);
                txtnombre.setText(aux.Nombre);
                txtdireccion.setText(aux.direccion);
                txtcredito.setText(aux.credito);
                txtcontra.setText(aux.contrasena);
                txtcorreo.setText(aux.correo);*/
            }
            anterior=posicion_actual;
            posicion_actual = posicion_actual.siguiente;
        } while (posicion_actual != Proyecto2IPC1.estudiante.primero);
    }//GEN-LAST:event_beliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beliminar;
    private javax.swing.JButton bobtener;
    private javax.swing.JButton bsalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcontra;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtcredito;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdpi;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
