/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2ipc1;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class MenuPrincipal extends javax.swing.JFrame {

  
    public MenuPrincipal(String title) {
        super(title);
        initComponents();
        
        setLocationRelativeTo(null);
        
        ImageIcon logousac2;
        logousac2 = new ImageIcon(new ImageIcon(String.format("src/imagen/logousac.png")).getImage().getScaledInstance(logousac.getWidth(), logousac.getHeight(), Image.SCALE_DEFAULT));
        logousac.setIcon(logousac2);
        contenido.setText("<html>La Facultad de Ingeniería se dedica a la formación de profesionales de prestigio, cuyos conocimientos contribuyen al progreso científico y tecnológico de Guatemala.\n" +
"\n" +
"     \n" +
"\n" +
"    En esta unidad académica se desempeñan seis escuelas facultativas de pregrado que disponen de doce carreras, una escuela de postgrado con carácter regional centroamericano; además, del Centro de Investigaciones de Ingeniería (CII), "
                + "de manera que su proyección es amplia hacia diversas actividades económicas y sociales del país.<html>");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonlogin = new javax.swing.JButton();
        botonAbout = new javax.swing.JButton();
        contenido = new javax.swing.JLabel();
        logousac = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        botonlogin.setBackground(new java.awt.Color(0, 204, 0));
        botonlogin.setText("Login");
        botonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonloginActionPerformed(evt);
            }
        });
        jPanel1.add(botonlogin);
        botonlogin.setBounds(430, 30, 140, 50);

        botonAbout.setBackground(new java.awt.Color(255, 153, 0));
        botonAbout.setText("About");
        jPanel1.add(botonAbout);
        botonAbout.setBounds(50, 310, 140, 50);

        contenido.setText("jLabel1");
        jPanel1.add(contenido);
        contenido.setBounds(280, 90, 300, 280);

        logousac.setText("1321");
        jPanel1.add(logousac);
        logousac.setBounds(20, 70, 250, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal("Menu").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbout;
    private javax.swing.JButton botonlogin;
    private javax.swing.JLabel contenido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logousac;
    // End of variables declaration//GEN-END:variables
}
