/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2ipc1;

/**
 *
 * @author USUARIO
 */
public class ModificarEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form ModificarEstudiante
     */
    NodoEstudiante aux;

    public ModificarEstudiante() {
        initComponents();

        //Bloquear TextField
        bdpi.setEditable(false);
        bcontra.setEditable(false);
        
        //////////////////////////MOSTRAR CARNET EN COMBOBOX///////////////////////////////////////////
        aux = Proyecto2IPC1.estudiante.primero;
        do {
            jComboBox1.addItem(aux.carnet);
            aux = aux.siguiente;
        } while (aux != Proyecto2IPC1.estudiante.primero);
        
        /////////////////////////////////////////////////////////////////////

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bdpi = new javax.swing.JTextField();
        bnombre = new javax.swing.JTextField();
        bapellido = new javax.swing.JTextField();
        bdireccion = new javax.swing.JTextField();
        bcreditos = new javax.swing.JTextField();
        bcontra = new javax.swing.JTextField();
        bcorreo = new javax.swing.JTextField();
        bmodificar = new javax.swing.JButton();
        bsalir = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        bobtener = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Modificar Estudiante");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 11, 350, 60);

        jLabel2.setText("Carnet");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 90, 70, 20);

        jLabel3.setText("Dpi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 140, 60, 20);

        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 190, 70, 20);

        jLabel5.setText("Apellido");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 240, 70, 20);

        jLabel6.setText("Direccion");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(270, 90, 70, 20);

        jLabel7.setText("No.Creditos");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(270, 140, 80, 20);

        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 190, 80, 20);

        jLabel9.setText("Correo");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 240, 70, 20);
        jPanel1.add(bdpi);
        bdpi.setBounds(80, 140, 160, 30);
        jPanel1.add(bnombre);
        bnombre.setBounds(80, 190, 160, 30);
        jPanel1.add(bapellido);
        bapellido.setBounds(80, 240, 160, 30);
        jPanel1.add(bdireccion);
        bdireccion.setBounds(340, 90, 170, 30);
        jPanel1.add(bcreditos);
        bcreditos.setBounds(340, 140, 170, 30);
        jPanel1.add(bcontra);
        bcontra.setBounds(340, 190, 170, 30);

        bcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcorreoActionPerformed(evt);
            }
        });
        jPanel1.add(bcorreo);
        bcorreo.setBounds(340, 240, 170, 30);

        bmodificar.setBackground(new java.awt.Color(51, 255, 0));
        bmodificar.setText("Modificar");
        bmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodificarActionPerformed(evt);
            }
        });
        jPanel1.add(bmodificar);
        bmodificar.setBounds(220, 300, 110, 50);

        bsalir.setBackground(new java.awt.Color(255, 0, 0));
        bsalir.setText("Salir");
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });
        jPanel1.add(bsalir);
        bsalir.setBounds(390, 300, 100, 50);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(80, 90, 160, 30);

        bobtener.setText("Obtener");
        bobtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bobtenerActionPerformed(evt);
            }
        });
        jPanel1.add(bobtener);
        bobtener.setBounds(60, 300, 110, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcorreoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void bobtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bobtenerActionPerformed
        // TODO add your handling code here:
        
        aux = Proyecto2IPC1.estudiante.primero;
        do {
            if(jComboBox1.getSelectedItem()==aux.carnet){
                bdpi.setText(aux.dpi);
                bapellido.setText(aux.Apellido);
                bnombre.setText(aux.Nombre);
                bdireccion.setText(aux.direccion);
                bcreditos.setText(aux.credito);
                bcontra.setText(aux.contrasena);
                bcorreo.setText(aux.correo);
            }
            aux = aux.siguiente;
        } while (aux != Proyecto2IPC1.estudiante.primero);
        
    }//GEN-LAST:event_bobtenerActionPerformed

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        // TODO add your handling code here:
        AdministrarEstudiantes administrador = new AdministrarEstudiantes();
        administrador.setVisible(true);
        ModificarEstudiante.this.dispose();
    }//GEN-LAST:event_bsalirActionPerformed

    private void bmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodificarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_bmodificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField bapellido;
    private javax.swing.JTextField bcontra;
    public static javax.swing.JTextField bcorreo;
    private javax.swing.JTextField bcreditos;
    public static javax.swing.JTextField bdireccion;
    private javax.swing.JTextField bdpi;
    private javax.swing.JButton bmodificar;
    public static javax.swing.JTextField bnombre;
    private javax.swing.JButton bobtener;
    private javax.swing.JButton bsalir;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
